/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trivia;

/**
 *
 * @author 628037
 */
public class GameBoard2 extends javax.swing.JFrame {
    int Score;
    int whichQuestion;
    /**
     * Creates new form GameBoard
     */
    public GameBoard2(int score) {
        initComponents();
        Score = score;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        categoryName1 = new javax.swing.JLabel();
        categoryName2 = new javax.swing.JLabel();
        categoryName3 = new javax.swing.JLabel();
        categoryName4 = new javax.swing.JLabel();
        categoryName5 = new javax.swing.JLabel();
        artist1 = new javax.swing.JButton();
        artist2 = new javax.swing.JButton();
        artist3 = new javax.swing.JButton();
        artist4 = new javax.swing.JButton();
        artist5 = new javax.swing.JButton();
        lyrics1 = new javax.swing.JButton();
        lyrics2 = new javax.swing.JButton();
        lyrics3 = new javax.swing.JButton();
        lyrics4 = new javax.swing.JButton();
        lyrics5 = new javax.swing.JButton();
        album1 = new javax.swing.JButton();
        album2 = new javax.swing.JButton();
        album3 = new javax.swing.JButton();
        album4 = new javax.swing.JButton();
        album5 = new javax.swing.JButton();
        women1 = new javax.swing.JButton();
        women2 = new javax.swing.JButton();
        women3 = new javax.swing.JButton();
        women4 = new javax.swing.JButton();
        women5 = new javax.swing.JButton();
        years1 = new javax.swing.JButton();
        years2 = new javax.swing.JButton();
        years3 = new javax.swing.JButton();
        years4 = new javax.swing.JButton();
        years5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        answerBox = new javax.swing.JTextField();
        scoreBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkAnswer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 38)); // NOI18N
        title.setForeground(new java.awt.Color(250, 218, 218));
        title.setText(" MUSIC TRIVIA ");
        title.setOpaque(true);

        categoryName1.setBackground(new java.awt.Color(0, 0, 0));
        categoryName1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 26)); // NOI18N
        categoryName1.setForeground(new java.awt.Color(250, 218, 218));
        categoryName1.setText(" GRAMMYs ");
        categoryName1.setOpaque(true);

        categoryName2.setBackground(new java.awt.Color(0, 0, 0));
        categoryName2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 26)); // NOI18N
        categoryName2.setForeground(new java.awt.Color(255, 218, 218));
        categoryName2.setText(" AMAs ");
        categoryName2.setOpaque(true);

        categoryName3.setBackground(new java.awt.Color(0, 0, 0));
        categoryName3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 26)); // NOI18N
        categoryName3.setForeground(new java.awt.Color(255, 218, 218));
        categoryName3.setText(" Juno Awards ");
        categoryName3.setOpaque(true);

        categoryName4.setBackground(new java.awt.Color(0, 0, 0));
        categoryName4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 26)); // NOI18N
        categoryName4.setForeground(new java.awt.Color(250, 218, 218));
        categoryName4.setText(" CMAs ");
        categoryName4.setOpaque(true);

        categoryName5.setBackground(new java.awt.Color(0, 0, 0));
        categoryName5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 26)); // NOI18N
        categoryName5.setForeground(new java.awt.Color(250, 218, 218));
        categoryName5.setText(" VMAs ");
        categoryName5.setOpaque(true);

        artist1.setBackground(new java.awt.Color(250, 218, 218));
        artist1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist1.setText("200");
        artist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist1ActionPerformed(evt);
            }
        });

        artist2.setBackground(new java.awt.Color(250, 218, 218));
        artist2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist2.setText("400");
        artist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist2ActionPerformed(evt);
            }
        });

        artist3.setBackground(new java.awt.Color(250, 218, 218));
        artist3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist3.setText("600");
        artist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist3ActionPerformed(evt);
            }
        });

        artist4.setBackground(new java.awt.Color(250, 218, 218));
        artist4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist4.setText("800");
        artist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist4ActionPerformed(evt);
            }
        });

        artist5.setBackground(new java.awt.Color(250, 218, 218));
        artist5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist5.setText("1000");
        artist5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist5ActionPerformed(evt);
            }
        });

        lyrics1.setBackground(new java.awt.Color(250, 218, 218));
        lyrics1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics1.setText("200");
        lyrics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics1ActionPerformed(evt);
            }
        });

        lyrics2.setBackground(new java.awt.Color(250, 218, 218));
        lyrics2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics2.setText("400");
        lyrics2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics2ActionPerformed(evt);
            }
        });

        lyrics3.setBackground(new java.awt.Color(250, 218, 218));
        lyrics3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics3.setText("600");
        lyrics3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics3ActionPerformed(evt);
            }
        });

        lyrics4.setBackground(new java.awt.Color(250, 218, 218));
        lyrics4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics4.setText("800");
        lyrics4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics4ActionPerformed(evt);
            }
        });

        lyrics5.setBackground(new java.awt.Color(250, 218, 218));
        lyrics5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics5.setText("1000");
        lyrics5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics5ActionPerformed(evt);
            }
        });

        album1.setBackground(new java.awt.Color(250, 218, 218));
        album1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album1.setText("200");
        album1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album1ActionPerformed(evt);
            }
        });

        album2.setBackground(new java.awt.Color(250, 218, 218));
        album2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album2.setText("400");
        album2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album2ActionPerformed(evt);
            }
        });

        album3.setBackground(new java.awt.Color(250, 218, 218));
        album3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album3.setText("600");
        album3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album3ActionPerformed(evt);
            }
        });

        album4.setBackground(new java.awt.Color(250, 218, 218));
        album4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album4.setText("800");
        album4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album4ActionPerformed(evt);
            }
        });

        album5.setBackground(new java.awt.Color(250, 218, 218));
        album5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album5.setText("1000");
        album5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album5ActionPerformed(evt);
            }
        });

        women1.setBackground(new java.awt.Color(250, 218, 218));
        women1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women1.setText("200");
        women1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women1ActionPerformed(evt);
            }
        });

        women2.setBackground(new java.awt.Color(250, 218, 218));
        women2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women2.setText("400");
        women2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women2ActionPerformed(evt);
            }
        });

        women3.setBackground(new java.awt.Color(250, 218, 218));
        women3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women3.setText("600");
        women3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women3ActionPerformed(evt);
            }
        });

        women4.setBackground(new java.awt.Color(250, 218, 218));
        women4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women4.setText("800");
        women4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women4ActionPerformed(evt);
            }
        });

        women5.setBackground(new java.awt.Color(250, 218, 218));
        women5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women5.setText("1000");
        women5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women5ActionPerformed(evt);
            }
        });

        years1.setBackground(new java.awt.Color(250, 218, 218));
        years1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years1.setText("200");
        years1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years1ActionPerformed(evt);
            }
        });

        years2.setBackground(new java.awt.Color(250, 218, 218));
        years2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years2.setText("400");
        years2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years2ActionPerformed(evt);
            }
        });

        years3.setBackground(new java.awt.Color(250, 218, 218));
        years3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years3.setText("600");
        years3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years3ActionPerformed(evt);
            }
        });

        years4.setBackground(new java.awt.Color(250, 218, 218));
        years4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years4.setText("800");
        years4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years4ActionPerformed(evt);
            }
        });

        years5.setBackground(new java.awt.Color(250, 218, 218));
        years5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years5.setText("1000");
        years5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years5ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 218, 218));
        jLabel2.setText(" QUESTION ");
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 218, 218));
        jLabel1.setText(" YOUR ANSWER ");
        jLabel1.setOpaque(true);

        answerBox.setBackground(new java.awt.Color(0, 0, 0));
        answerBox.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        answerBox.setForeground(new java.awt.Color(250, 218, 218));
        answerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBoxActionPerformed(evt);
            }
        });

        scoreBox.setBackground(new java.awt.Color(0, 0, 0));
        scoreBox.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        scoreBox.setForeground(new java.awt.Color(250, 218, 218));
        scoreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBoxActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 218, 218));
        jLabel3.setText(" SCORE ");
        jLabel3.setOpaque(true);

        checkAnswer.setBackground(new java.awt.Color(250, 218, 218));
        checkAnswer.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        checkAnswer.setText("CHECK ANSWER");
        checkAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(250, 218, 218));

        questionDisplay.setBackground(new java.awt.Color(0, 0, 0));
        questionDisplay.setColumns(20);
        questionDisplay.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        questionDisplay.setForeground(new java.awt.Color(250, 218, 218));
        questionDisplay.setRows(5);
        jScrollPane1.setViewportView(questionDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel1)))
                        .addGap(100, 100, 100)
                        .addComponent(scoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(450, 450, 450))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkAnswer)
                        .addGap(429, 429, 429))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(artist2)
                                            .addComponent(artist3)
                                            .addComponent(artist4)
                                            .addComponent(artist5)
                                            .addComponent(artist1)))
                                    .addComponent(categoryName1))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lyrics1)
                                        .addComponent(categoryName2)
                                        .addComponent(lyrics2)
                                        .addComponent(lyrics3)
                                        .addComponent(lyrics4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lyrics5)))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(album2)
                                            .addComponent(album3)
                                            .addComponent(album4)
                                            .addComponent(album5)
                                            .addComponent(album1)))
                                    .addComponent(categoryName3))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(women2)
                                    .addComponent(women3)
                                    .addComponent(women4)
                                    .addComponent(women5)
                                    .addComponent(women1)
                                    .addComponent(categoryName4))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(years2)
                                    .addComponent(years3)
                                    .addComponent(years4)
                                    .addComponent(years5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(categoryName5)
                                        .addComponent(years1)))))
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(title)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(categoryName3)
                            .addGap(18, 18, 18)
                            .addComponent(album1)
                            .addGap(18, 18, 18)
                            .addComponent(album2)
                            .addGap(18, 18, 18)
                            .addComponent(album3)
                            .addGap(18, 18, 18)
                            .addComponent(album4)
                            .addGap(18, 18, 18)
                            .addComponent(album5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(categoryName2)
                            .addGap(18, 18, 18)
                            .addComponent(lyrics1)
                            .addGap(18, 18, 18)
                            .addComponent(lyrics2)
                            .addGap(18, 18, 18)
                            .addComponent(lyrics3)
                            .addGap(18, 18, 18)
                            .addComponent(lyrics4)
                            .addGap(18, 18, 18)
                            .addComponent(lyrics5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(categoryName4)
                            .addGap(18, 18, 18)
                            .addComponent(women1)
                            .addGap(18, 18, 18)
                            .addComponent(women2)
                            .addGap(18, 18, 18)
                            .addComponent(women3)
                            .addGap(18, 18, 18)
                            .addComponent(women4)
                            .addGap(18, 18, 18)
                            .addComponent(women5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(categoryName5)
                            .addGap(18, 18, 18)
                            .addComponent(years1)
                            .addGap(18, 18, 18)
                            .addComponent(years2)
                            .addGap(18, 18, 18)
                            .addComponent(years3)
                            .addGap(18, 18, 18)
                            .addComponent(years4)
                            .addGap(18, 18, 18)
                            .addComponent(years5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryName1)
                        .addGap(18, 18, 18)
                        .addComponent(artist1)
                        .addGap(18, 18, 18)
                        .addComponent(artist2)
                        .addGap(18, 18, 18)
                        .addComponent(artist3)
                        .addGap(18, 18, 18)
                        .addComponent(artist4)
                        .addGap(18, 18, 18)
                        .addComponent(artist5)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scoreBox, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(answerBox, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkAnswer)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                          
    private void artist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What living artist has the most Grammys?");
        answerBox.getText();
        whichQuestion = 2;
        this.remove(artist2);
        repaint();
    }//GEN-LAST:event_artist2ActionPerformed

    private void artist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who presents the Grammys each year?");
        answerBox.getText();
        whichQuestion = 1;
        this.remove(artist1);
        repaint();
    }//GEN-LAST:event_artist1ActionPerformed

    private void artist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In what year were the first Grammys held?");
        answerBox.getText();
        whichQuestion = 3;
        this.remove(artist3);
        repaint();
    }//GEN-LAST:event_artist3ActionPerformed

    private void artist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Daily Double!!! How many pounds does a Grammy Award Weigh?");
        answerBox.getText();
        whichQuestion = 4;
        this.remove(artist4);
        repaint();
    }//GEN-LAST:event_artist4ActionPerformed

    private void artist5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who is the youngest person to win a Grammy?");
        answerBox.getText();
        whichQuestion = 5;
        this.remove(artist5);
        repaint();
    }//GEN-LAST:event_artist5ActionPerformed

    private void lyrics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who has the most AMA wins?");
        answerBox.getText();
        whichQuestion = 6;
        this.remove(lyrics1);
        repaint();
    }//GEN-LAST:event_lyrics1ActionPerformed

    private void lyrics2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In 2013 the first ‘Icon Award’ was presented. Who was the first artist to receive this award?");
        answerBox.getText();
        whichQuestion = 7;
        this.remove(lyrics2);
        repaint();
    }//GEN-LAST:event_lyrics2ActionPerformed

    private void lyrics3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who hosted the AMAs every year from 2005-2008?");
        answerBox.getText();
        whichQuestion = 8;
        this.remove(lyrics3);
        repaint();
    }//GEN-LAST:event_lyrics3ActionPerformed

    private void lyrics4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In what year were the AMAs first presented?");
        answerBox.getText();
        whichQuestion = 9;
        this.remove(lyrics4);
        repaint();
    }//GEN-LAST:event_lyrics4ActionPerformed

    private void lyrics5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What artist performed on a flaming piano in 2009?");
        answerBox.getText();
        whichQuestion = 10;
        this.remove(lyrics5);
        repaint();
    }//GEN-LAST:event_lyrics5ActionPerformed

    private void album1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What other awards show are the Juno Awards compared to?");
        answerBox.getText();
        whichQuestion = 11;
        this.remove(album1);
        repaint();
    }//GEN-LAST:event_album1ActionPerformed

    private void album2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What artist has had the most nominations to date?");
        answerBox.getText();
        whichQuestion = 12;
        this.remove(album2);
        repaint();
    }//GEN-LAST:event_album2ActionPerformed

    private void album3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What are the Juno awards named after?");
        answerBox.getText();
        whichQuestion = 13;
        this.remove(album3);
        repaint();
    }//GEN-LAST:event_album3ActionPerformed

    private void album4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In what year were the Juno Awards first presented?");
        answerBox.getText();
        whichQuestion = 14;
        this.remove(album4);
        repaint();
    }//GEN-LAST:event_album4ActionPerformed

    private void album5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("How many different awards are given each year?");
        answerBox.getText();
        whichQuestion = 15;
        this.remove(album5);
        repaint();
    }//GEN-LAST:event_album5ActionPerformed

    private void women1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What does CMA stand for?");
        answerBox.getText();
        whichQuestion = 16;
        this.remove(women1);
        repaint();
    }//GEN-LAST:event_women1ActionPerformed

    private void women2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who has the most CMA wins?");
        answerBox.getText();
        whichQuestion = 17;
        this.remove(women2);
        repaint();
    }//GEN-LAST:event_women2ActionPerformed

    private void women3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In what year were the first CMAs held?");
        answerBox.getText();
        whichQuestion = 18;
        this.remove(women3);
        repaint();
    }//GEN-LAST:event_women3ActionPerformed

    private void women4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In what month do the CMAs take place each year?");
        answerBox.getText();
        whichQuestion = 19;
        this.remove(women4);
        repaint();
    }//GEN-LAST:event_women4ActionPerformed

    private void women5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("How many times have Carrie Underwood and Brad Paisley hosted the CMAs?");
        answerBox.getText();
        whichQuestion = 20;
        this.remove(women5);
        repaint();
    }//GEN-LAST:event_women5ActionPerformed

    private void years1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who presents the VMAs every year?");
        answerBox.getText();
        whichQuestion = 21;
        this.remove(years1);
        repaint();
    }//GEN-LAST:event_years1ActionPerformed

    private void years2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Which artist has the most VMA wins?");
        answerBox.getText();
        whichQuestion = 22;
        this.remove(years2);
        repaint();
    }//GEN-LAST:event_years2ActionPerformed

    private void years3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("In 2009 this artist got on stage claiming that Beyonce deserved the VMA for Best Female Video more "
                + "than Taylor Swift. Who was it?");
        answerBox.getText();
        whichQuestion = 23;
        this.remove(years3);
        repaint();
    }//GEN-LAST:event_years3ActionPerformed

    private void years4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What year were the first VMAs held?");
        answerBox.getText();
        whichQuestion = 24;
        this.remove(years4);
        repaint();
    }//GEN-LAST:event_years4ActionPerformed

    private void years5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What New York City venue has hosted the most VMAs?");
        answerBox.getText();
        whichQuestion = 25;
        this.remove(years5);
        repaint();
    }//GEN-LAST:event_years5ActionPerformed

    private void answerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBoxActionPerformed

    private void scoreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_scoreBoxActionPerformed

    private void checkAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerActionPerformed
        // TODO add your handling code here:
        if (whichQuestion  == 1 ){
            if ("The Recording Academy".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 1 ){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 2 ){
            if ("Quincy Jones".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 2 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 3 ){
            if ("1959".equalsIgnoreCase(answerBox.getText())){
                Score += 600;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 3 ){
                    Score -=  600;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 4 ){
            if ("6 pounds".equalsIgnoreCase(answerBox.getText())){
                Score += 1600;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 4 ){
                    Score -=  1600;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 5 ){
            if ("LeAnn Rimes".equalsIgnoreCase(answerBox.getText())){
                Score += 1000;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 5 ){
                    Score -=  1000;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 6 ){
            if ("Micheal Jackson".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 6 ){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 7 ){
            if ("Rihanna".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 7 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 8 ){
            if ("Jimmy Kimmel".equalsIgnoreCase(answerBox.getText())){
                Score += 600;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 8 ){
                    Score -=  600;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 9 ){
            if ("1974".equalsIgnoreCase(answerBox.getText())){
                Score += 800;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 9 ){
                    Score -=  800;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 10 ){
            if ("Lady Gaga".equalsIgnoreCase(answerBox.getText())){
                Score += 1000;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 10 ){
                    Score -=  1000;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 11){
            if ("Grammys".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 11){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 12) {
            if ("Anne Murray".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 12) {
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 13 ){
            if ("Pierre Juneau".equalsIgnoreCase(answerBox.getText())){
                Score += 600;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 13 ){
                    Score -=  600;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 14 ){
            if ("1970".equalsIgnoreCase(answerBox.getText())){
                Score += 800;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 14 ){
                    Score -=  800;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 15 ){
            if ("43".equalsIgnoreCase(answerBox.getText())){
                Score += 1000;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 15 ){
                    Score -=  1000;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 16 ){
            if ("Country Music Awards".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 16 ){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 17 ){
            if ("Garth Brooks".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 17 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 18 ){
            if ("1967".equalsIgnoreCase(answerBox.getText())){
                Score += 600;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 18 ){
                    Score -=  600;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 19 ){
            if ("November".equalsIgnoreCase(answerBox.getText())){
                Score += 800;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 19 ){
                    Score -=  800;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 20) {
            if ("6 times".equalsIgnoreCase(answerBox.getText())){
                Score += 1000;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 20) {
                    Score -=  1000;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 21) {
            if ("MTV".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 21) {
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 22) {
            if ("Madonna".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 22) {
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 23) {
            if ("Kanye West".equalsIgnoreCase(answerBox.getText())){
                Score += 600;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 23) {
                    Score -=  600;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 24) {
            if ("1984".equalsIgnoreCase(answerBox.getText())){
                Score += 800;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 24) {
                    Score -=  800;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 25) {
            if ("Radio City Music Hall".equalsIgnoreCase(answerBox.getText())){
                Score += 1000;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 25) {
                    Score -=  1000;
                    scoreBox.setText(" " + Score);
                } 
        }
        answerBox.setText("");
    }//GEN-LAST:event_checkAnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton album1;
    private javax.swing.JButton album2;
    private javax.swing.JButton album3;
    private javax.swing.JButton album4;
    private javax.swing.JButton album5;
    private javax.swing.JTextField answerBox;
    private javax.swing.JButton artist1;
    private javax.swing.JButton artist2;
    private javax.swing.JButton artist3;
    private javax.swing.JButton artist4;
    private javax.swing.JButton artist5;
    private javax.swing.JLabel categoryName1;
    private javax.swing.JLabel categoryName2;
    private javax.swing.JLabel categoryName3;
    private javax.swing.JLabel categoryName4;
    private javax.swing.JLabel categoryName5;
    private javax.swing.JButton checkAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lyrics1;
    private javax.swing.JButton lyrics2;
    private javax.swing.JButton lyrics3;
    private javax.swing.JButton lyrics4;
    private javax.swing.JButton lyrics5;
    private javax.swing.JTextArea questionDisplay;
    private javax.swing.JTextField scoreBox;
    private javax.swing.JLabel title;
    private javax.swing.JButton women1;
    private javax.swing.JButton women2;
    private javax.swing.JButton women3;
    private javax.swing.JButton women4;
    private javax.swing.JButton women5;
    private javax.swing.JButton years1;
    private javax.swing.JButton years2;
    private javax.swing.JButton years3;
    private javax.swing.JButton years4;
    private javax.swing.JButton years5;
    // End of variables declaration//GEN-END:variables
}
