/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trivia;

/**
 *
 * @author 628037
 */
public class GameBoard extends javax.swing.JFrame {
    int Score;
    int whichQuestion;
    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        categoryName1 = new javax.swing.JLabel();
        categoryName2 = new javax.swing.JLabel();
        categoryName3 = new javax.swing.JLabel();
        categoryName4 = new javax.swing.JLabel();
        categoryName5 = new javax.swing.JLabel();
        artist1 = new javax.swing.JButton();
        artist2 = new javax.swing.JButton();
        artist3 = new javax.swing.JButton();
        artist4 = new javax.swing.JButton();
        artist5 = new javax.swing.JButton();
        lyrics1 = new javax.swing.JButton();
        lyrics2 = new javax.swing.JButton();
        lyrics3 = new javax.swing.JButton();
        lyrics4 = new javax.swing.JButton();
        lyrics5 = new javax.swing.JButton();
        album1 = new javax.swing.JButton();
        album2 = new javax.swing.JButton();
        album3 = new javax.swing.JButton();
        album4 = new javax.swing.JButton();
        album5 = new javax.swing.JButton();
        women1 = new javax.swing.JButton();
        women2 = new javax.swing.JButton();
        women3 = new javax.swing.JButton();
        women4 = new javax.swing.JButton();
        women5 = new javax.swing.JButton();
        years1 = new javax.swing.JButton();
        years2 = new javax.swing.JButton();
        years3 = new javax.swing.JButton();
        years4 = new javax.swing.JButton();
        years5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        answerBox = new javax.swing.JTextField();
        scoreBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkAnswer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionDisplay = new javax.swing.JTextArea();
        doubleTrivia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 38)); // NOI18N
        title.setForeground(new java.awt.Color(250, 218, 218));
        title.setText(" MUSIC TRIVIA ");
        title.setOpaque(true);

        categoryName1.setBackground(new java.awt.Color(0, 0, 0));
        categoryName1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        categoryName1.setForeground(new java.awt.Color(250, 218, 218));
        categoryName1.setText(" NAME THAT ARTIST ");
        categoryName1.setOpaque(true);

        categoryName2.setBackground(new java.awt.Color(0, 0, 0));
        categoryName2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        categoryName2.setForeground(new java.awt.Color(255, 218, 218));
        categoryName2.setText(" FILL IN THE LYRICS ");
        categoryName2.setOpaque(true);

        categoryName3.setBackground(new java.awt.Color(0, 0, 0));
        categoryName3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        categoryName3.setForeground(new java.awt.Color(255, 218, 218));
        categoryName3.setText(" ALBUM TRIVIA ");
        categoryName3.setOpaque(true);

        categoryName4.setBackground(new java.awt.Color(0, 0, 0));
        categoryName4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        categoryName4.setForeground(new java.awt.Color(250, 218, 218));
        categoryName4.setText(" WOMEN IN MUSIC ");
        categoryName4.setOpaque(true);

        categoryName5.setBackground(new java.awt.Color(0, 0, 0));
        categoryName5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        categoryName5.setForeground(new java.awt.Color(250, 218, 218));
        categoryName5.setText(" MUSIC THROUGH THE YEARS ");
        categoryName5.setOpaque(true);

        artist1.setBackground(new java.awt.Color(250, 218, 218));
        artist1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist1.setText("100");
        artist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist1ActionPerformed(evt);
            }
        });

        artist2.setBackground(new java.awt.Color(250, 218, 218));
        artist2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist2.setText("200");
        artist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist2ActionPerformed(evt);
            }
        });

        artist3.setBackground(new java.awt.Color(250, 218, 218));
        artist3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist3.setText("300");
        artist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist3ActionPerformed(evt);
            }
        });

        artist4.setBackground(new java.awt.Color(250, 218, 218));
        artist4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist4.setText("400");
        artist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist4ActionPerformed(evt);
            }
        });

        artist5.setBackground(new java.awt.Color(250, 218, 218));
        artist5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        artist5.setText("500");
        artist5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist5ActionPerformed(evt);
            }
        });

        lyrics1.setBackground(new java.awt.Color(250, 218, 218));
        lyrics1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics1.setText("100");
        lyrics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics1ActionPerformed(evt);
            }
        });

        lyrics2.setBackground(new java.awt.Color(250, 218, 218));
        lyrics2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics2.setText("200");
        lyrics2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics2ActionPerformed(evt);
            }
        });

        lyrics3.setBackground(new java.awt.Color(250, 218, 218));
        lyrics3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics3.setText("300");
        lyrics3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics3ActionPerformed(evt);
            }
        });

        lyrics4.setBackground(new java.awt.Color(250, 218, 218));
        lyrics4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics4.setText("400");
        lyrics4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics4ActionPerformed(evt);
            }
        });

        lyrics5.setBackground(new java.awt.Color(250, 218, 218));
        lyrics5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        lyrics5.setText("500");
        lyrics5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrics5ActionPerformed(evt);
            }
        });

        album1.setBackground(new java.awt.Color(250, 218, 218));
        album1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album1.setText("100");
        album1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album1ActionPerformed(evt);
            }
        });

        album2.setBackground(new java.awt.Color(250, 218, 218));
        album2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album2.setText("200");
        album2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album2ActionPerformed(evt);
            }
        });

        album3.setBackground(new java.awt.Color(250, 218, 218));
        album3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album3.setText("300");
        album3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album3ActionPerformed(evt);
            }
        });

        album4.setBackground(new java.awt.Color(250, 218, 218));
        album4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album4.setText("400");
        album4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album4ActionPerformed(evt);
            }
        });

        album5.setBackground(new java.awt.Color(250, 218, 218));
        album5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        album5.setText("500");
        album5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album5ActionPerformed(evt);
            }
        });

        women1.setBackground(new java.awt.Color(250, 218, 218));
        women1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women1.setText("100");
        women1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women1ActionPerformed(evt);
            }
        });

        women2.setBackground(new java.awt.Color(250, 218, 218));
        women2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women2.setText("200");
        women2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women2ActionPerformed(evt);
            }
        });

        women3.setBackground(new java.awt.Color(250, 218, 218));
        women3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women3.setText("300");
        women3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women3ActionPerformed(evt);
            }
        });

        women4.setBackground(new java.awt.Color(250, 218, 218));
        women4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women4.setText("400");
        women4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women4ActionPerformed(evt);
            }
        });

        women5.setBackground(new java.awt.Color(250, 218, 218));
        women5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        women5.setText("500");
        women5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                women5ActionPerformed(evt);
            }
        });

        years1.setBackground(new java.awt.Color(250, 218, 218));
        years1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years1.setText("100");
        years1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years1ActionPerformed(evt);
            }
        });

        years2.setBackground(new java.awt.Color(250, 218, 218));
        years2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years2.setText("200");
        years2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years2ActionPerformed(evt);
            }
        });

        years3.setBackground(new java.awt.Color(250, 218, 218));
        years3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years3.setText("300");
        years3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years3ActionPerformed(evt);
            }
        });

        years4.setBackground(new java.awt.Color(250, 218, 218));
        years4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years4.setText("400");
        years4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years4ActionPerformed(evt);
            }
        });

        years5.setBackground(new java.awt.Color(250, 218, 218));
        years5.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        years5.setText("500");
        years5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years5ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 218, 218));
        jLabel2.setText(" QUESTION ");
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 218, 218));
        jLabel1.setText(" YOUR ANSWER ");
        jLabel1.setOpaque(true);

        answerBox.setBackground(new java.awt.Color(0, 0, 0));
        answerBox.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        answerBox.setForeground(new java.awt.Color(250, 218, 218));
        answerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBoxActionPerformed(evt);
            }
        });

        scoreBox.setBackground(new java.awt.Color(0, 0, 0));
        scoreBox.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        scoreBox.setForeground(new java.awt.Color(250, 218, 218));
        scoreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBoxActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 218, 218));
        jLabel3.setText(" SCORE ");
        jLabel3.setOpaque(true);

        checkAnswer.setBackground(new java.awt.Color(250, 218, 218));
        checkAnswer.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        checkAnswer.setText("CHECK ANSWER");
        checkAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(250, 218, 218));

        questionDisplay.setBackground(new java.awt.Color(0, 0, 0));
        questionDisplay.setColumns(20);
        questionDisplay.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        questionDisplay.setForeground(new java.awt.Color(250, 218, 218));
        questionDisplay.setRows(5);
        jScrollPane1.setViewportView(questionDisplay);

        doubleTrivia.setBackground(new java.awt.Color(250, 218, 218));
        doubleTrivia.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        doubleTrivia.setText("Double Trivia");
        doubleTrivia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleTriviaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 218, 218));
        jLabel4.setText(" ONCE YOU'RE DONE, CLICK HERE: ");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(artist2)
                                .addComponent(artist3)
                                .addComponent(artist4)
                                .addComponent(artist5))
                            .addComponent(artist1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lyrics2)
                            .addComponent(lyrics3)
                            .addComponent(lyrics4)
                            .addComponent(lyrics5)
                            .addComponent(lyrics1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(album2)
                                .addComponent(album3)
                                .addComponent(album4)
                                .addComponent(album5))
                            .addComponent(album1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(categoryName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categoryName2)
                        .addGap(115, 115, 115)
                        .addComponent(categoryName3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(women2)
                            .addComponent(women3)
                            .addComponent(women4)
                            .addComponent(women5)
                            .addComponent(women1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(years1)
                            .addComponent(years2)
                            .addComponent(years3)
                            .addComponent(years4)
                            .addComponent(years5))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(categoryName4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categoryName5)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(254, 254, 254)
                .addComponent(jLabel3)
                .addGap(165, 165, 165))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkAnswer)
                .addGap(487, 487, 487))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(answerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(scoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(491, 491, 491)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(doubleTrivia)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doubleTrivia)
                            .addComponent(jLabel4))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryName1)
                    .addComponent(categoryName2)
                    .addComponent(categoryName3)
                    .addComponent(categoryName4)
                    .addComponent(categoryName5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artist1)
                    .addComponent(lyrics1)
                    .addComponent(album1)
                    .addComponent(women1)
                    .addComponent(years1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(years2)
                        .addGap(18, 18, 18)
                        .addComponent(years3)
                        .addGap(18, 18, 18)
                        .addComponent(years4)
                        .addGap(18, 18, 18)
                        .addComponent(years5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(women2)
                        .addGap(18, 18, 18)
                        .addComponent(women3)
                        .addGap(18, 18, 18)
                        .addComponent(women4)
                        .addGap(18, 18, 18)
                        .addComponent(women5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(album2)
                        .addGap(18, 18, 18)
                        .addComponent(album3)
                        .addGap(18, 18, 18)
                        .addComponent(album4)
                        .addGap(18, 18, 18)
                        .addComponent(album5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lyrics2)
                        .addGap(18, 18, 18)
                        .addComponent(lyrics3)
                        .addGap(18, 18, 18)
                        .addComponent(lyrics4)
                        .addGap(18, 18, 18)
                        .addComponent(lyrics5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(artist2)
                        .addGap(18, 18, 18)
                        .addComponent(artist3)
                        .addGap(18, 18, 18)
                        .addComponent(artist4)
                        .addGap(18, 18, 18)
                        .addComponent(artist5)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoreBox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAnswer)
                .addGap(159, 159, 159))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                          
    private void artist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What female pop artist got their start "
                + "on the Broadway musical, 13?");
        answerBox.getText();
        whichQuestion = 2;
        this.remove(artist2);
        repaint();
    }//GEN-LAST:event_artist2ActionPerformed

    private void artist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Which American actor performs music under "
                + "the stage name Childish Gambino?");
        answerBox.getText();
        whichQuestion = 1;
        this.remove(artist1);
        repaint();
    }//GEN-LAST:event_artist1ActionPerformed

    private void artist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who is the only artist to have 4 number 1’s "
                + "on the adult pop charts before the age of 20?");
        answerBox.getText();
        whichQuestion = 3;
        this.remove(artist3);
        repaint();
    }//GEN-LAST:event_artist3ActionPerformed

    private void artist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What artist became popular by uploading their song on "
                + "Soundcloud for their dance teacher to choreograph dance to?");
        answerBox.getText();
        whichQuestion = 4;
        this.remove(artist4);
        repaint();
    }//GEN-LAST:event_artist4ActionPerformed

    private void artist5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("DAILY DOUBLE!!! This R&B artist wrote and released one song a month starting in 2016 for 12 months. "
                + "This resulted with his debut album being released in November 2017.");
        answerBox.getText();
        whichQuestion = 5;
        this.remove(artist5);
        repaint();
    }//GEN-LAST:event_artist5ActionPerformed

    private void lyrics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("No One - Alicia Keys: 'you and me together "
                + "through the days and nights I don’t worry ‘cause…'");
        answerBox.getText();
        whichQuestion = 6;
        this.remove(lyrics1);
        repaint();
    }//GEN-LAST:event_lyrics1ActionPerformed

    private void lyrics2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Love Story - Taylor Swift: 'So I sneak out to the garden to see "
                + "you. We keep quiet ‘cause we’re dead if they knew…'");
        answerBox.getText();
        whichQuestion = 7;
        this.remove(lyrics2);
        repaint();
    }//GEN-LAST:event_lyrics2ActionPerformed

    private void lyrics3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Justin Timberlake - What Goes Around: 'It’s breakin’ my heart to "
                + "watch you run around. ‘Cause I know that you’re living a lie…'");
        answerBox.getText();
        whichQuestion = 8;
        this.remove(lyrics3);
        repaint();
    }//GEN-LAST:event_lyrics3ActionPerformed

    private void lyrics4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Oops I Did it Again - Britney Spears: 'I think I did it again. "
                + "I made you believe we‘re more than just friends. Oh baby…'");
        answerBox.getText();
        whichQuestion = 9;
        this.remove(lyrics4);
        repaint();
    }//GEN-LAST:event_lyrics4ActionPerformed

    private void lyrics5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrics5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Independent Woman - Destiny’s Child: 'Question: tell "
                + "me what you think about me I buy my own diamonds and…'");
        answerBox.getText();
        whichQuestion = 10;
        this.remove(lyrics5);
        repaint();
    }//GEN-LAST:event_lyrics5ActionPerformed

    private void album1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What album had the highest stream and sales data, making it number 1 for the year, in 2002?");
        answerBox.getText();
        whichQuestion = 11;
        this.remove(album1);
        repaint();
    }//GEN-LAST:event_album1ActionPerformed

    private void album2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What album had the highest stream and sales data, making it number 1 for the year, in 2008?");
        answerBox.getText();
        whichQuestion = 12;
        this.remove(album2);
        repaint();
    }//GEN-LAST:event_album2ActionPerformed

    private void album3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What album had the highest stream and sales data, making it number 1 for the year, in 2012?");
        answerBox.getText();
        whichQuestion = 13;
        this.remove(album3);
        repaint();
    }//GEN-LAST:event_album3ActionPerformed

    private void album4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What album had the highest stream and sales data, making it number 1 for the year, in 2016?");
        answerBox.getText();
        whichQuestion = 14;
        this.remove(album4);
        repaint();
    }//GEN-LAST:event_album4ActionPerformed

    private void album5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What album had the highest stream and sales data, making it number 1 for the year, in 2018?");
        answerBox.getText();
        whichQuestion = 15;
        this.remove(album5);
        repaint();
    }//GEN-LAST:event_album5ActionPerformed

    private void women1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who was the first women to be inducted into the Rock and Roll Hall of Fame?");
        answerBox.getText();
        whichQuestion = 16;
        this.remove(women1);
        repaint();
    }//GEN-LAST:event_women1ActionPerformed

    private void women2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("As of 2019 who was the youngest person (and 4th woman) to headline Coachella?");
        answerBox.getText();
        whichQuestion = 17;
        this.remove(women2);
        repaint();
    }//GEN-LAST:event_women2ActionPerformed

    private void women3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who was the first women to replace themself at the number 1 on the Hot 100 chart?");
        answerBox.getText();
        whichQuestion = 18;
        this.remove(women3);
        repaint();
    }//GEN-LAST:event_women3ActionPerformed

    private void women4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Her tour became the highest grossing tour by a solo female artist in 2009 with $408 million in box-office receipts.");
        answerBox.getText();
        whichQuestion = 19;
        this.remove(women4);
        repaint();
    }//GEN-LAST:event_women4ActionPerformed

    private void women5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_women5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("She’s the only artist in history to have been nominated for an Academy Award, a Grammy Award, a Brit Award, "
                + "a Mercury Prize, and an Alternative Turner Prize.");
        answerBox.getText();
        whichQuestion = 20;
        this.remove(women5);
        repaint();
    }//GEN-LAST:event_women5ActionPerformed

    private void years1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years1ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What song spent the most time at number 1 during the 1980s?");
        answerBox.getText();
        whichQuestion = 21;
        this.remove(years1);
        repaint();
    }//GEN-LAST:event_years1ActionPerformed

    private void years2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years2ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What song spent the most amount of time at number 1 during the 1990s?");
        answerBox.getText();
        whichQuestion = 22;
        this.remove(years2);
        repaint();
    }//GEN-LAST:event_years2ActionPerformed

    private void years3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years3ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("These two songs tied for the most time at number 1 during the 2000s. What songs were they?");
        answerBox.getText();
        whichQuestion = 23;
        this.remove(years3);
        repaint();
    }//GEN-LAST:event_years3ActionPerformed

    private void years4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years4ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("What song has spent the most time at number 1 so far during the 2010s?");
        answerBox.getText();
        whichQuestion = 24;
        this.remove(years4);
        repaint();
    }//GEN-LAST:event_years4ActionPerformed

    private void years5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years5ActionPerformed
        // TODO add your handling code here:
        questionDisplay.setText("Who were the most streamed artists in 2018? (one male, one female)");
        answerBox.getText();
        whichQuestion = 25;
        this.remove(years5);
        repaint();
    }//GEN-LAST:event_years5ActionPerformed

    private void answerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBoxActionPerformed

    private void scoreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_scoreBoxActionPerformed

    private void checkAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerActionPerformed
        // TODO add your handling code here:
   
        if (whichQuestion  == 1 ){
            if ("Donald Glover".equalsIgnoreCase(answerBox.getText())){
                Score += 100;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 1 ){
                    Score -=  100;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 2 ){
            if ("Ariana Grande".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 2 ){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 3 ){
            if ("Shawn Mendes".equalsIgnoreCase(answerBox.getText())){
                Score += 300;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 3 ){
                    Score -=  300;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 4 ){
            if ("Billie Eilish".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 4 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 5 ){
            if ("Bruno Major".equalsIgnoreCase(answerBox.getText())){
                Score += 1000;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 5 ){
                    Score -=  1000;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 6 ){
            if ("Everything's gonna be alright".equalsIgnoreCase(answerBox.getText())){
                Score += 100;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 6 ){
                    Score -=  100;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 7 ){
            if ("So close your eyes, escape this town for a little while".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 7 ){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 8 ){
            if ("But that’s okay, baby, ‘cause in time you will find what goes around, goes around, goes around comes all the way back around".equalsIgnoreCase(answerBox.getText())){
                Score += 300;
                scoreBox.setText(" " + Score); 
            }
                else if(whichQuestion  == 8 ){
                    Score -=  300;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 9 ){
            if ("It might seem like a crush, but it doesn’t mean that I’m serious".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 9 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 10 ){
            if ("I buy my own rings".equalsIgnoreCase(answerBox.getText())){
                Score += 500;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 10 ){
                    Score -=  500;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 11){
            if ("The Eminem Show".equalsIgnoreCase(answerBox.getText())){
                Score += 100;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 11){
                    Score -=  100;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 12) {
            if ("As I Am".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 12) {
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 13 ){
            if ("21".equalsIgnoreCase(answerBox.getText())){
                Score += 300;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 13 ){
                    Score -=  300;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 14 ){
            if ("25".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 14 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 15 ){
            if ("Reputation".equalsIgnoreCase(answerBox.getText())){
                Score += 500;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 15 ){
                    Score -=  500;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 16 ){
            if ("Aretha Franklin".equalsIgnoreCase(answerBox.getText())){
                Score += 100;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 16 ){
                    Score -=  100;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 17 ){
            if ("Ariana Grande".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 17 ){
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 18 ){
            if ("Taylor Swift".equalsIgnoreCase(answerBox.getText())){
                Score += 300;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 18 ){
                    Score -=  300;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 19 ){
            if ("Madonna".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 19 ){
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 20) {
            if ("M.I.A".equalsIgnoreCase(answerBox.getText())){
                Score += 500;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 20) {
                    Score -=  500;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 21) {
            if ("Physical".equalsIgnoreCase(answerBox.getText())){
                Score += 100;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 21) {
                    Score -=  100;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 22) {
            if ("One Sweet Day".equalsIgnoreCase(answerBox.getText())){
                Score += 200;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 22) {
                    Score -=  200;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 23) {
            if ("I gotta Feeling and We Belong Together".equalsIgnoreCase(answerBox.getText())){
                Score += 300;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 23) {
                    Score -=  300;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 24) {
            if ("Despacito".equalsIgnoreCase(answerBox.getText())){
                Score += 400;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 24) {
                    Score -=  400;
                    scoreBox.setText(" " + Score);
                } 
        }
        if (whichQuestion  == 25) {
            if ("Drake and Ariana Grande".equalsIgnoreCase(answerBox.getText())){
                Score += 500;
                scoreBox.setText(" " + Score); 
            }
                else if (whichQuestion  == 25) {
                    Score -=  500;
                    scoreBox.setText(" " + Score);
                } 
        }
             answerBox.setText("");
    }//GEN-LAST:event_checkAnswerActionPerformed

    private void doubleTriviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleTriviaActionPerformed
        // TODO add your handling code here:
        new GameBoard2(Score).setVisible(true);
    }//GEN-LAST:event_doubleTriviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton album1;
    private javax.swing.JButton album2;
    private javax.swing.JButton album3;
    private javax.swing.JButton album4;
    private javax.swing.JButton album5;
    private javax.swing.JTextField answerBox;
    private javax.swing.JButton artist1;
    private javax.swing.JButton artist2;
    private javax.swing.JButton artist3;
    private javax.swing.JButton artist4;
    private javax.swing.JButton artist5;
    private javax.swing.JLabel categoryName1;
    private javax.swing.JLabel categoryName2;
    private javax.swing.JLabel categoryName3;
    private javax.swing.JLabel categoryName4;
    private javax.swing.JLabel categoryName5;
    private javax.swing.JButton checkAnswer;
    private javax.swing.JButton doubleTrivia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lyrics1;
    private javax.swing.JButton lyrics2;
    private javax.swing.JButton lyrics3;
    private javax.swing.JButton lyrics4;
    private javax.swing.JButton lyrics5;
    private javax.swing.JTextArea questionDisplay;
    private javax.swing.JTextField scoreBox;
    private javax.swing.JLabel title;
    private javax.swing.JButton women1;
    private javax.swing.JButton women2;
    private javax.swing.JButton women3;
    private javax.swing.JButton women4;
    private javax.swing.JButton women5;
    private javax.swing.JButton years1;
    private javax.swing.JButton years2;
    private javax.swing.JButton years3;
    private javax.swing.JButton years4;
    private javax.swing.JButton years5;
    // End of variables declaration//GEN-END:variables
}
